# rssget default configuration file

# RSS item display ordering. Order by "date" or by "channel".
display_by: date

# channels to retrieve
channels:
  - url: "example.com/rss"
    # (optional) alias for this rss
    alias: "Example RSS"
    # (optional) max max number of items to show
    max_items: 10
    # (optional) display configuration for Items of a Channel (default: all false)
    item_config:
      hide_title: false
      hide_link: false
      hide_description: false
      hide_author: false
      hide_pub_date: false
      show_enclosure: false
  - url: "otherexample.com/rss"